[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "advent_of_code_python"
version = "1.0.0"

[project.scripts]
solve_AoC_day = "solutions.run_day_solution:main"